name: ogmp
channels:
  - defaults
  - conda-forge
  - fvcore
  - iopath
  - bottler
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2024.8.30=py38h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=6.1.1=hecf7045_5
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fvcore=0.1.5.post20210915=py38
  - giflib=5.2.2=h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - iopath=0.1.9=py38
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=h42c8aad_2
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=h4cb591d_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.5=h7934f7d_0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - nvidiacub=1.10.0=0
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.46=hf426167_0
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pixman=0.46.4=h7934f7d_0
  - portalocker=2.10.1=py38h578d9bd_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=he870216_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py38h2019614_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.3=py38h06a4308_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=0.11.0=py38_cu113
  - torchvision=0.12.0=py38_cu113
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - urllib3=2.2.3=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - antlr4-python3-runtime==4.9.3
      - bps-torch==0.1
      - chamfer-distance==0.1
      - click==8.1.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - dotmap==1.3.30
      - einops==0.4.1
      - ema-pytorch==0.0.10
      - fonttools==4.57.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - imageio==2.19.3
      - imageio-ffmpeg==0.4.7
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - loguru==0.7.3
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - networkx==3.1
      - ninja==1.13.0
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pathtools==0.1.2
      - promise==2.3
      - protobuf==3.20.3
      - psutil==7.1.3
      - pygments==2.19.2
      - pyopengl==3.1.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch3d==0.7.2
      - pywavelets==1.4.1
      - rich==14.2.0
      - scenepic==1.0.8
      - scikit-image==0.20.0
      - scikit-learn==1.3.2
      - scipy==1.9.1
      - sentry-sdk==2.45.0
      - setproctitle==1.3.7
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - torchgeometry==0.1.2
      - trimesh==4.9.0
      - wandb==0.12.21
      - zipp==3.20.2
prefix: /home/learning/miniconda3/envs/ogmp
