root_dir: "/media/learning/DATA/export_smplx_retargeted_clothesstand"

sample:
  # Checkpoints
  stage1_ckpt: "/home/learning/Documents/g1-diffusion/logs/stage1_e10000_b5_lr0.0001_ts1000_w120_s10_transformer_2025Dec22_05-35-08/checkpoints/stage1_epoch_002889.pt"
  stage2_ckpt: "/home/learning/Documents/g1-diffusion/logs/stage2_e10000_b5_lr0.0001_ts1000_w120_s10_transformer_2025Dec22_05-34-21/checkpoints/stage2_epoch_004699.pt"  # Path to Stage 2 checkpoint
  
  num_samples: 10
  timesteps: 1000
  device: "cuda"
  random_samples: true
  seed: 42
  
  # Contact constraints (applied between Stage 1 and Stage 2)
  apply_constraints: true
  contact_threshold: 0.03
  hand_marker_radius: 0.02

dataset:
  window_size: 120
  stride: 10
  min_seq_len: 32
  train: false
  train_split: 0.9
  preload: false
