root_dir: "/home/learning/Documents/g1-gmr/export_smplx_retargeted"

sample:
  # Checkpoints
  stage1_ckpt: "/home/learning/Documents/g1-diffusion/logs/stage1_e10000_b5_lr0.0001_ts1000_w120_s10_transformer_2025Dec13_17-18-00/checkpoints/stage1_epoch_003999.pt"  # Path to Stage 1 checkpoint
  stage2_ckpt: "/home/learning/Documents/g1-diffusion/logs/stage2_e10000_b5_lr0.0001_ts1000_w120_s10_transformer_2025Dec13_17-18-16/checkpoints/stage2_epoch_004499.pt"  # Path to Stage 2 checkpoint
  
  num_samples: 5
  timesteps: 1000
  device: "cuda"
  random_samples: false
  seed: 42
  
  # Contact constraints (applied between Stage 1 and Stage 2)
  apply_constraints: true
  contact_threshold: 0.03
  hand_marker_radius: 0.02

dataset:
  window_size: 120
  stride: 10
  min_seq_len: 32
  train: false
  train_split: 0.9
  preload: false
